name: Timeline Merge Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: node_modules/eslint/bin/eslint.js  --ext .ts server
    - run: node_modules/eslint/bin/eslint.js  --ext .ts typings
    - run: node_modules/tslint/bin/tslint -p ./ -c server/tslint.json
    - run: node_modules/typescript/bin/tsc -p ./
    - run: rm -r dist
